#!/usr/bin/env python3
"""Builds src/canvas.js from page/canvas.src.js, the Tamzen fonts and the cards.

The device loads one script, so the fonts and the 1,000 cards travel inside it
as data. This fills the two placeholders in the source:

    /*@FONTS@*/null   the five Tamzen sizes, ASCII 32..126
    /*@CARDS@*/null   cards/elusive-muse.txt, one card per line

Glyph format: [left, top, w, row0, row1, ...]. `left` and `top` place the
glyph's box relative to its cell's left edge and its line's top; each row is
a bitmask, most significant bit leftmost.

    scripts/gen_canvas.py           write src/canvas.js
    scripts/gen_canvas.py --check   exit 1 if src/canvas.js is out of date
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIZES = ["10x20", "8x16", "7x14", "6x12", "5x9"]


def read_bdf(path):
    lines = open(path, encoding="latin-1").read().split("\n")
    asc = desc = 0
    glyphs = {}
    dw_all = None
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("FONT_ASCENT"):
            asc = int(line.split()[1])
        elif line.startswith("FONT_DESCENT"):
            desc = int(line.split()[1])
        elif line.startswith("STARTCHAR"):
            enc = bbx = dw = None
            rows = []
            while not lines[i].startswith("ENDCHAR"):
                t = lines[i]
                if t.startswith("ENCODING"):
                    enc = int(t.split()[1])
                elif t.startswith("DWIDTH"):
                    dw = int(t.split()[1])
                elif t.startswith("BBX"):
                    bbx = list(map(int, t.split()[1:]))
                elif t == "BITMAP":
                    i += 1
                    while not lines[i].startswith("ENDCHAR"):
                        rows.append(int(lines[i], 16))
                        i += 1
                    break
                i += 1
            if enc is not None and 32 <= enc <= 126:
                w, h, xo, yo = bbx
                padded = ((w + 7) // 8) * 8
                masks = [r >> (padded - w) for r in rows]
                # Trim empty rows top and bottom: same pixels, less data.
                top = asc - (h + yo)
                while masks and masks[0] == 0:
                    masks.pop(0)
                    top += 1
                while masks and masks[-1] == 0:
                    masks.pop()
                glyphs[chr(enc)] = [xo, top, w] + masks
                if dw_all is None:
                    dw_all = dw
                elif dw != dw_all:
                    sys.exit(f"{path}: not monospaced ({chr(enc)!r} is {dw}, not {dw_all})")
        i += 1
    return {"dw": dw_all, "asc": asc, "desc": desc, "g": glyphs}


def build():
    fonts = {s: read_bdf(os.path.join(ROOT, "fonts", "tamzen", f"Tamzen{s}r.bdf")) for s in SIZES}
    cards = [l.strip() for l in open(os.path.join(ROOT, "cards", "elusive-muse.txt"), encoding="utf-8")]
    cards = [c for c in cards if c]
    for c in cards:
        bad = [ch for ch in c if not (32 <= ord(ch) <= 126)]
        if bad:
            sys.exit(f"card has characters the fonts lack: {c!r} {bad}")
    src = open(os.path.join(ROOT, "page", "canvas.src.js"), encoding="utf-8").read()
    for ph in ("/*@FONTS@*/null", "/*@CARDS@*/null"):
        if src.count(ph) != 1:
            sys.exit(f"page/canvas.src.js: placeholder {ph} must appear exactly once")
    head = ("/* GENERATED by scripts/gen_canvas.py from page/canvas.src.js, fonts/tamzen\n"
            " * and cards/elusive-muse.txt. Do not edit; edit those and regenerate. */\n")
    fonts_js = "{\n" + ",\n".join(
        f'        "{s}": {{"dw":{f["dw"]},"asc":{f["asc"]},"desc":{f["desc"]},"g":'
        + json.dumps(f["g"], separators=(",", ":")) + "}"
        for s, f in fonts.items()) + "\n    }"
    cards_js = "[\n" + ",\n".join("        " + json.dumps(c) for c in cards) + "\n    ]"
    return head + src.replace("/*@FONTS@*/null", fonts_js).replace("/*@CARDS@*/null", cards_js)


def main():
    out = build()
    path = os.path.join(ROOT, "src", "canvas.js")
    if "--check" in sys.argv:
        cur = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if cur != out:
            print("src/canvas.js is out of date: run scripts/gen_canvas.py", file=sys.stderr)
            sys.exit(1)
        return
    open(path, "w", encoding="utf-8").write(out)
    print(f"wrote src/canvas.js ({len(out)} bytes)")


if __name__ == "__main__":
    main()
